let cards = [

{
name:"Quent Johnson",
image:"cards/quent_johnson.png",
total:100000,
team:"Volt Runners",
height:"6'3",
weight:"208 lbs",
position:"WR",
set:"Basic",
logo:"images/logos/runners.png",
college:"TCU",
nextSerial: 1
},
{
name:"Jorge Dickens",
image:"cards/jorge_dickens.png",
total:100000,
team:"Lone Star Outlaws",
height:"6'3",
weight:"200 lbs",
position:"WR",
set:"Basic",
logo:"images/logos/outlaws.png",
college:"UGA",
nextSerial: 1
},
{
name:"X Flowers",
image:"cards/x_flowers.png",
total:100000,
team:"Shadow Ravens",
height:"5'9",
weight:"183 lbs",
position:"WR",
set:"Basic",
logo:"images/logos/ravens.png",
college:"BC",
nextSerial: 1
},
{
name:"Erick Stinger Jr.",
image:"cards/erick_stinger_jr.png",
total:100000,
team:"Lone Star Phantoms",
height:"6'0",
weight:"195 lbs",
position:"CB",
set:"Basic",
logo:"images/logos/phantoms.png",
college:"LSU",
nextSerial: 1
},
{
name:"William Andson Jr.",
image:"cards/william_andson_jr.png",
total:100000,
team:"Lone Star Phantoms",
height:"6'4",
weight:"243 lbs",
position:"DE",
set:"Basic",
logo:"images/logos/phantoms.png",
college:"UA",
nextSerial: 1
},
{
name:"CD Sheep",
image:"cards/cd_sheep.png",
total:100000,
team:"Lone Star Outlaws",
height:"6'2",
weight:"200 lbs",
position:"WR",
set:"Basic",
logo:"images/logos/outlaws.png",
college:"OU",
nextSerial: 1
},
{
name:"Marv Harry Jr.",
image:"cards/marv_jr.png",
total:100000,
team:"Desert Vultures",
height:"6'3",
weight:"220 lbs",
position:"WR",
set:"Basic",
logo:"images/logos/vultures.png",
college:"OSU",
nextSerial: 1
},
{
name:"Tray Mc",
image:"cards/tray.png",
total:100000,
team:"Desert Vultures",
height:"6'4",
weight:"246 lbs",
position:"TE",
set:"Basic",
logo:"images/logos/vultures.png",
college:"CAM",
nextSerial: 1
},
{
name:"BJan Obinson",
image:"cards/bj.png",
total:100000,
team:"Sky Reapers",
height:"5'11",
weight:"216 lbs",
position:"RB",
set:"Basic",
logo:"images/logos/sky.png",
college:"TEXAS",
nextSerial: 1
},
{
name:"Drake England",
image:"cards/drake.png",
total:100000,
team:"Sky Reapers",
height:"6'4",
weight:"215 lbs",
position:"WR",
set:"Basic",
logo:"images/logos/sky.png",
college:"USC",
nextSerial: 1
},
{
name:"Chub Hubs",
image:"cards/chubs.png",
total:100000,
team:"Storm Prowlers",
height:"6'0",
weight:"209 lbs",
position:"RB",
set:"Basic",
logo:"images/logos/storm.png",
college:"POKES",
nextSerial: 1
},
{
name:"Tet Milan",
image:"cards/tet.png",
total:100000,
team:"Storm Prowlers",
height:"6'5",
weight:"212 lbs",
position:"WR",
set:"Basic",
logo:"images/logos/storm.png",
college:"U of A",
nextSerial: 1
},
{
name:"Ome Unze",
image:"cards/ome.png",
total:100000,
team:"Midwest Titans",
height:"6'0",
weight:"214 lbs",
position:"WR",
set:"Basic",
logo:"images/logos/titans.png",
college:"UW",
nextSerial: 1
},
{
name:"Kaleb Liams",
image:"cards/kaleb.png",
total:100000,
team:"Midwest Titans",
height:"6'1",
weight:"226 lbs",
position:"QB",
set:"Basic",
logo:"images/logos/titans.png",
college:"USC",
nextSerial: 1
},
{
name:"Jah Gib",
image:"cards/jah.png",
total:100000,
team:"Motor City Kings",
height:"5'9",
weight:"202 lbs",
position:"RB",
set:"Basic",
logo:"images/logos/motor.png",
college:"UA",
nextSerial: 1
},
{
name:"Dan Hutch",
image:"cards/dan.png",
total:100000,
team:"Motor City Kings",
height:"6'7",
weight:"269 lbs",
position:"DE",
set:"Basic",
logo:"images/logos/motor.png",
college:"UMich",
nextSerial: 1
},
{
name:"Josh Cobbs",
image:"cards/josh.png",
total:100000,
team:"The Bay Cheeseheads",
height:"5'10",
weight:"223 lbs",
position:"RB",
set:"Basic",
logo:"images/logos/cheesehead.png",
college:"UA",
nextSerial: 1
},
{
name:"Mike Pars",
image:"cards/pars.png",
total:100000,
team:"The Bay Cheeseheads",
height:"6'3",
weight:"250 lbs",
position:"DL",
set:"Basic",
logo:"images/logos/cheesehead.png",
college:"PSU",
nextSerial: 1
},
{
name:"Uka Cua",
image:"cards/uka.png",
total:100000,
team:"Coastal Horns",
height:"6'2",
weight:"216 lbs",
position:"WR",
set:"Basic",
logo:"images/logos/horns.png",
college:"BYU",
nextSerial: 1
},
{
name:"Mat Ford",
image:"cards/mat.png",
total:100000,
team:"Coastal Horns",
height:"6'3",
weight:"214 lbs",
position:"QB",
set:"Basic",
logo:"images/logos/horns.png",
college:"UAG",
nextSerial: 1
},
{
name:"Jets Jeferson",
image:"cards/jets.png",
total:100000,
team:"Northern Warhawks",
height:"6'0",
weight:"194 lbs",
position:"WR",
set:"Basic",
logo:"images/logos/northern.png",
college:"LSU",
nextSerial: 1
},
{
name:"Isa Rodgers",
image:"cards/isa.png",
total:100000,
team:"Northern Warhawks",
height:"5'10",
weight:"180 lbs",
position:"CB",
set:"Basic",
logo:"images/logos/northern.png",
college:"UMass",
nextSerial: 1
},
{
name:"Kris Lave",
image:"cards/lave.png",
total:100000,
team:"Bayou Royals",
height:"6'0",
weight:"187 lbs",
position:"WR",
set:"Basic",
logo:"images/logos/royals.png",
college:"OSU",
nextSerial: 1
},
{
name:"Trav E. Tien",
image:"cards/tien.png",
total:100000,
team:"Bayou Royals",
height:"5'10",
weight:"215 lbs",
position:"RB",
set:"Basic",
logo:"images/logos/royals.png",
college:"CLEM",
nextSerial: 1
},
{
name:"Leek Neighbors",
image:"cards/leek.png",
total:100000,
team:"Empire Guardians",
height:"6'0",
weight:"200 lbs",
position:"WR",
set:"Basic",
logo:"images/logos/empire.png",
college:"LSU",
nextSerial: 1
},
{
name:"Kam Skat",
image:"cards/skat.png",
total:100000,
team:"Empire Guardians",
height:"5'9",
weight:"220 lbs",
position:"RB",
set:"Basic",
logo:"images/logos/empire.png",
college:"ASU",
nextSerial: 1
}
]