let cards = [

{
name:"Quent Johnson",
image:"cards/quent_johnson.png",
total:50,
team:"Volt Runners",
height:"6'3",
weight:"208 lbs",
position:"WR",
set:"Basic",
logo:"images/logos/runners.png",
college:"TCU",
nextSerial: 1
},
{
name:"Jorge Dickens",
image:"cards/jorge_dickens.png",
total:50,
team:"Lone Star Outlaws",
height:"6'3",
weight:"200 lbs",
position:"WR",
set:"Basic",
logo:"images/logos/outlaws.png",
college:"UGA",
nextSerial: 1
},
{
name:"X Flowers",
image:"cards/x_flowers.png",
total:50,
team:"Shadow Ravens",
height:"5'9",
weight:"183 lbs",
position:"WR",
set:"Basic",
logo:"images/logos/ravens.png",
college:"BC",
nextSerial: 1
},
{
name:"Erick Stinger Jr.",
image:"cards/erick_stinger_jr.png",
total:50,
team:"Lone Star Phantoms",
height:"6'0",
weight:"195 lbs",
position:"CB",
set:"Basic",
logo:"images/logos/phantoms.png",
college:"LSU",
nextSerial: 1
},
{
name:"William Andson Jr.",
image:"cards/william_andson_jr.png",
total:50,
team:"Lone Star Phantoms",
height:"6'4",
weight:"243 lbs",
position:"DE",
set:"Basic",
logo:"images/logos/phantoms.png",
college:"UA",
nextSerial: 1
},
{
name:"CD Sheep",
image:"cards/cd_sheep.png",
total:50,
team:"Lone Star Outlaws",
height:"6'2",
weight:"200 lbs",
position:"WR",
set:"Basic",
logo:"images/logos/outlaws.png",
college:"OU",
nextSerial: 1
},
{
name:"Marv Harry Jr.",
image:"cards/marv_jr.png",
total:50,
team:"Desert Vultures",
height:"6'3",
weight:"220 lbs",
position:"WR",
set:"Basic",
logo:"images/logos/vultures.png",
college:"OSU",
nextSerial: 1
},
{
name:"Tray Mc",
image:"cards/tray.png",
total:50,
team:"Desert Vultures",
height:"6'4",
weight:"246 lbs",
position:"TE",
set:"Basic",
logo:"images/logos/vultures.png",
college:"CAM",
nextSerial: 1
},
{
name:"BJan Obinson",
image:"cards/bj.png",
total:50,
team:"Sky Reapers",
height:"5'11",
weight:"216 lbs",
position:"RB",
set:"Basic",
logo:"images/logos/sky.png",
college:"TEXAS",
nextSerial: 1
},
{
name:"Drake England",
image:"cards/drake.png",
total:50,
team:"Sky Reapers",
height:"6'4",
weight:"215 lbs",
position:"WR",
set:"Basic",
logo:"images/logos/sky.png",
college:"USC",
nextSerial: 1
},
{
name:"Chub Hubs",
image:"cards/chubs.png",
total:50,
team:"Storm Prowlers",
height:"6'0",
weight:"209 lbs",
position:"RB",
set:"Basic",
logo:"images/logos/storm.png",
college:"POKES",
nextSerial: 1
},
{
name:"Tet Milan",
image:"cards/tet.png",
total:50,
team:"Storm Prowlers",
height:"6'5",
weight:"212 lbs",
position:"WR",
set:"Basic",
logo:"images/logos/storm.png",
college:"U of A",
nextSerial: 1
},
{
name:"Ome Unze",
image:"cards/ome.png",
total:50,
team:"Midwest Titans",
height:"6'0",
weight:"214 lbs",
position:"WR",
set:"Basic",
logo:"images/logos/titans.png",
college:"UW",
nextSerial: 1
},
{
name:"Kaleb Liams",
image:"cards/kaleb.png",
total:50,
team:"Midwest Titans",
height:"6'1",
weight:"226 lbs",
position:"QB",
set:"Basic",
logo:"images/logos/titans.png",
college:"USC",
nextSerial: 1
},
{
name:"Jah Gib",
image:"cards/jah.png",
total:50,
team:"Motor City Kings",
height:"5'9",
weight:"202 lbs",
position:"RB",
set:"Basic",
logo:"images/logos/motor.png",
college:"UA",
nextSerial: 1
},
{
name:"Dan Hutch",
image:"cards/dan.png",
total:50,
team:"Motor City Kings",
height:"6'7",
weight:"269 lbs",
position:"DE",
set:"Basic",
logo:"images/logos/motor.png",
college:"UMich",
nextSerial: 1
},
{
name:"Josh Cobbs",
image:"cards/josh.png",
total:50,
team:"The Bay Cheeseheads",
height:"5'10",
weight:"223 lbs",
position:"RB",
set:"Basic",
logo:"images/logos/cheesehead.png",
college:"UA",
nextSerial: 1
},
{
name:"Mike Pars",
image:"cards/pars.png",
total:50,
team:"The Bay Cheeseheads",
height:"6'3",
weight:"250 lbs",
position:"DL",
set:"Basic",
logo:"images/logos/cheesehead.png",
college:"PSU",
nextSerial: 1
},
{
name:"Uka Cua",
image:"cards/uka.png",
total:50,
team:"Coastal Horns",
height:"6'2",
weight:"216 lbs",
position:"WR",
set:"Basic",
logo:"images/logos/horns.png",
college:"BYU",
nextSerial: 1
},
{
name:"Mat Ford",
image:"cards/mat.png",
total:50,
team:"Coastal Horns",
height:"6'3",
weight:"214 lbs",
position:"QB",
set:"Basic",
logo:"images/logos/horns.png",
college:"UAG",
nextSerial: 1
},
{
name:"Jets Jeferson",
image:"cards/jets.png",
total:50,
team:"Northern Warhawks",
height:"6'0",
weight:"194 lbs",
position:"WR",
set:"Basic",
logo:"images/logos/northern.png",
college:"LSU",
nextSerial: 1
},
{
name:"Isa Rodgers",
image:"cards/isa.png",
total:50,
team:"Northern Warhawks",
height:"5'10",
weight:"180 lbs",
position:"CB",
set:"Basic",
logo:"images/logos/northern.png",
college:"UMass",
nextSerial: 1
},
{
name:"Kris Lave",
image:"cards/lave.png",
total:50,
team:"Bayou Royals",
height:"6'0",
weight:"187 lbs",
position:"WR",
set:"Basic",
logo:"images/logos/royals.png",
college:"OSU",
nextSerial: 1
},
{
name:"Trav E. Tien",
image:"cards/tien.png",
total:50,
team:"Bayou Royals",
height:"5'10",
weight:"215 lbs",
position:"RB",
set:"Basic",
logo:"images/logos/royals.png",
college:"CLEM",
nextSerial: 1
},
{
name:"Leek Neighbors",
image:"cards/leek.png",
total:50,
team:"Empire Guardians",
height:"6'0",
weight:"200 lbs",
position:"WR",
set:"Basic",
logo:"images/logos/empire.png",
college:"LSU",
nextSerial: 1
},
{
name:"Kam Skat",
image:"cards/skat.png",
total:50,
team:"Empire Guardians",
height:"5'9",
weight:"220 lbs",
position:"RB",
set:"Basic",
logo:"images/logos/empire.png",
college:"ASU",
nextSerial: 1
},
{
name:"Quon Barkey",
image:"cards/quon.png",
total:50,
team:"Iron Talons",
height:"6'0",
weight:"233 lbs",
position:"RB",
set:"Basic",
logo:"images/logos/talons.png",
college:"PSU",
nextSerial: 1
},
{
name:"Jaylin Hurtz",
image:"cards/hurtz.png",
total:50,
team:"Iron Talons",
height:"6'1",
weight:"223 lbs",
position:"QB",
set:"Basic",
logo:"images/logos/talons.png",
college:"OU",
nextSerial: 1
},
{
name:"J-Den Niels",
image:"cards/niels.png",
total:50,
team:"Capital Sentinels",
height:"6'4",
weight:"210 lbs",
position:"QB",
set:"Basic",
logo:"images/logos/sentinels.png",
college:"LSU",
nextSerial: 1
},
{
name:"Terry Lauren",
image:"cards/terry.png",
total:50,
team:"Capital Sentinels",
height:"6'0",
weight:"210 lbs",
position:"WR",
set:"Basic",
logo:"images/logos/sentinels.png",
college:"OSU",
nextSerial: 1
},
{
name:"Chris McCaffe",
image:"cards/chris.png",
total:50,
team:"Golden Bay Bandits",
height:"5'11",
weight:"210 lbs",
position:"RB",
set:"Basic",
logo:"images/logos/bandits.png",
college:"SU",
nextSerial: 1
},
{
name:"George Kettle",
image:"cards/kettle.png",
total:50,
team:"Golden Bay Bandits",
height:"6'4",
weight:"250 lbs",
position:"TE",
set:"Basic",
logo:"images/logos/bandits.png",
college:"IOWA",
nextSerial: 1
},
{
name:"Jackson S. Nigba",
image:"cards/nigba.png",
total:50,
team:"Pacific Phantoms",
height:"6'0",
weight:"197 lbs",
position:"WR",
set:"Basic",
logo:"images/logos/pacific.png",
college:"OSU",
nextSerial: 1
},
{
name:"Devin Weatherspoon",
image:"cards/devin.png",
total:50,
team:"Pacific Phantoms",
height:"6'0",
weight:"185 lbs",
position:"CB",
set:"Basic",
logo:"images/logos/pacific.png",
college:"ILLINI",
nextSerial: 1
},
{
name:"Buck Iving",
image:"cards/buck.png",
total:50,
team:"Crimson Corsairs",
height:"5'10",
weight:"195 lbs",
position:"RB",
set:"Basic",
logo:"images/logos/crimson.png",
college:"UO",
nextSerial: 1
},
{
name:"Meka Buka",
image:"cards/meka.png",
total:50,
team:"Crimson Corsairs",
height:"6'0",
weight:"205 lbs",
position:"WR",
set:"Basic",
logo:"images/logos/crimson.png",
college:"OSU",
nextSerial: 1
},
{
name:"Patty Mahouse",
image:"cards/patty.png",
total:50,
team:"Prairie Monarchs",
height:"6'2",
weight:"225 lbs",
position:"QB",
set:"Basic",
logo:"images/logos/prairie.png",
college:"TTU",
nextSerial: 1
},
{
name:"Crashee Rice",
image:"cards/rice.png",
total:50,
team:"Prairie Monarchs",
height:"6'0",
weight:"203 lbs",
position:"WR",
set:"Basic",
logo:"images/logos/prairie.png",
college:"SMU",
nextSerial: 1
},
{
name:"Patek Surtan II",
image:"cards/surtan.png",
total:50,
team:"Rocky Ridge Riders",
height:"6'2",
weight:"202 lbs",
position:"CB",
set:"Basic",
logo:"images/logos/rocky.png",
college:"UA",
nextSerial: 1
},
{
name:"Nic Onitto",
image:"cards/nic.png",
total:50,
team:"Rocky Ridge Riders",
height:"6'3",
weight:"240 lbs",
position:"LB",
set:"Basic",
logo:"images/logos/rocky.png",
college:"OU",
nextSerial: 1
},
{
name:"Rock Browers",
image:"cards/rock.png",
total:50,
team:"Silver Syndicate",
height:"6'4",
weight:"235 lbs",
position:"TE",
set:"Basic",
logo:"images/logos/silver.png",
college:"UAG",
nextSerial: 1
},
{
name:"Ash Geanty",
image:"cards/ash.png",
total:50,
team:"Silver Syndicate",
height:"5'8",
weight:"208 lbs",
position:"RB",
set:"Basic",
logo:"images/logos/silver.png",
college:"BSU",
nextSerial: 1
},
{
name:"Darwin Jamie Jr.",
image:"cards/jamie.png",
total:50,
team:"Volt Runners",
height:"6'2",
weight:"216 lbs",
position:"S",
set:"Basic",
logo:"images/logos/runners.png",
college:"FSU",
nextSerial: 1
},
{
name:"Joshua Alan",
image:"cards/alan.png",
total:50,
team:"Arctic Stampede",
height:"6'5",
weight:"237 lbs",
position:"QB",
set:"Basic",
logo:"images/logos/arctic.png",
college:"UW",
nextSerial: 1
},
{
name:"Jamey Cooks",
image:"cards/cooks.png",
total:50,
team:"Arctic Stampede",
height:"5'11",
weight:"190 lbs",
position:"RB",
set:"Basic",
logo:"images/logos/arctic.png",
college:"UAG",
nextSerial: 1
},
{
name:"Jaylon Waddles",
image:"cards/waddles.png",
total:50,
team:"Ocean Surge",
height:"5'10",
weight:"185 lbs",
position:"WR",
set:"Basic",
logo:"images/logos/ocean.png",
college:"UA",
nextSerial: 1
},
{
name:"Von A. Chan",
image:"cards/von.png",
total:50,
team:"Ocean Surge",
height:"5'9",
weight:"191 lbs",
position:"RB",
set:"Basic",
logo:"images/logos/ocean.png",
college:"A&M",
nextSerial: 1
},
{
name:"Dake Mayes",
image:"cards/dake.png",
total:50,
team:"Liberty Phantoms",
height:"6'4",
weight:"225 lbs",
position:"QB",
set:"Basic",
logo:"images/logos/liberty.png",
college:"UNC",
nextSerial: 1
},
{
name:"Cristian Zolez",
image:"cards/zolez.png",
total:50,
team:"Liberty Phantoms",
height:"6'1",
weight:"205 lbs",
position:"CB",
set:"Basic",
logo:"images/logos/liberty.png",
college:"UO",
nextSerial: 1
},
{
name:"Gerat Willson",
image:"cards/gerat.png",
total:50,
team:"Skyline Aviators",
height:"6'0",
weight:"183 lbs",
position:"WR",
set:"Basic",
logo:"images/logos/skyline.png",
college:"OSU",
nextSerial: 1
},
{
name:"Reece Hull",
image:"cards/reece.png",
total:50,
team:"Skyline Aviators",
height:"5'11",
weight:"217 lbs",
position:"RB",
set:"Basic",
logo:"images/logos/skyline.png",
college:"ISU",
nextSerial: 1
},
{
name:"LaMar Jaxon",
image:"cards/lamar.png",
total:50,
team:"Shadow Ravens",
height:"6'2",
weight:"205 lbs",
position:"QB",
set:"Basic",
logo:"images/logos/ravens.png",
college:"UofL",
nextSerial: 1
},
{
name:"Joseph Barrow",
image:"cards/barrow.png",
total:50,
team:"Jungle Strikers",
height:"6'4",
weight:"216 lbs",
position:"QB",
set:"Basic",
logo:"images/logos/jungle.png",
college:"LSU",
nextSerial: 1
},
{
name:"J'Marr Case",
image:"cards/case.png",
total:50,
team:"Jungle Strikers",
height:"6'0",
weight:"205 lbs",
position:"WR",
set:"Basic",
logo:"images/logos/jungle.png",
college:"LSU",
nextSerial: 1
}
]